"""
Django settings for pangeos project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i))ov+u77_z(_ib3pn7h&dg++5e+f2&q3av!)ol^=aqy8x+!gb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'admin_sistema',
    'admin_datos',
    'explotacion_datos',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# New backend for authentication
AUTHENTICATION_BACKENDS = ['admin_sistema.backend.UserAuthentificacionBackend', 'django.contrib.auth.backends.ModelBackend',]

# Substituting a custom User model
AUTH_USER_MODEL = 'admin_sistema.Usuario'

ROOT_URLCONF = 'pangeos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pangeos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'BD_USUARIO',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': 'mongodb://usrdbadmin:yXr.K9fRYh@10.249.21.180:27017/?authSource=BD_USUARIO&readPreference=primary&appname=MongoDB%20Compass&ssl=false'
        }  
    },
    'BD_PANGEOSMX': {
        'ENGINE': 'djongo',
        'NAME': 'BD_PANGEOSMX',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': 'mongodb://pangeosdbadmin:yM9diZc2p$@10.249.21.180:27017/?authSource=BD_PANGEOSMX&readPreference=primary&appname=MongoDB%20Compass&ssl=false'
        }
    }
}
DATABASE_ROUTERS = ['pangeos.db_routers.DBRouter.DBRouter']


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = '/var/www/pangeos.com/static/' #( BASE_DIR / 'staticfiles' )
STATICFILES_DIRS = [ BASE_DIR / 'static' ]
PATH_FILES_IMAGES = [ BASE_DIR / 'static/images' ]
PATH_FILESKML = [ BASE_DIR / 'static/kmls' ] #PATH_FILESKML = '/var/www/pangeos.com/static/kmls'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Settings email Gmail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'anarim7@gmail.com'
EMAIL_HOST_PASSWORD = '?_ablo.pich/15'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'anarim7@gmail.com' 

#Login for browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
]

#Settings CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',    
    'token',
]

#Settings redirect Auth
LOGIN_REDIRECT_URL  =  '/' 
LOGOUT_REDIRECT_URL  =  '/'

# ENVIRONMENT VARIABLES
# - Time if the password recovery request
TIME_PASSWORD_RECOVERY_REQUEST = 259200 # seconds (1hr=3600s, 3600s*72h=259200)

PATH_BASE = "C:/Django Proyects/PANGEOS_DOWN_ENE2023/pangeos.com/" #var/www/pangeos.com/