# Generated by Django 3.2.8 on 2022-01-04 18:05

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEntidadFederativa',
            fields=[
                ('cveentidadFederativa', models.BigAutoField(db_column='CVE_ENTIDAD_FEDERATIVA', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
                ('abreviacion', models.CharField(db_column='ABREVIACION', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
                'db_table': 'Cat_Entidad_Federativa',
            },
        ),
        migrations.CreateModel(
            name='CatEscolaridad',
            fields=[
                ('cveescolaridad', models.BigAutoField(db_column='CVE_ESCOLARIDAD', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Escolaridades',
                'db_table': 'Cat_Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='CatEstatus',
            fields=[
                ('estatus', models.BigAutoField(db_column='CVE_ESTATUS', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Estatus',
                'db_table': 'Cat_Estatus',
            },
        ),
        migrations.CreateModel(
            name='CatInstitucion',
            fields=[
                ('cveinstitucion', models.BigAutoField(db_column='CVE_INSTITUCION', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Instituciones',
                'db_table': 'Cat_Institucion',
            },
        ),
        migrations.CreateModel(
            name='CatPerfil',
            fields=[
                ('cveperfil', models.BigAutoField(db_column='CVE_PERFIL', primary_key=True, serialize=False)),
                ('perfil', models.CharField(db_column='PERFIL', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
                'db_table': 'Cat_Perfil',
            },
        ),
        migrations.CreateModel(
            name='CatSexo',
            fields=[
                ('cvesexo', models.BigAutoField(db_column='CVE_SEXO', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=1)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sexos',
                'db_table': 'Cat_Sexo',
            },
        ),
        migrations.CreateModel(
            name='HistoricoUsuario',
            fields=[
                ('cveusuario', models.BigAutoField(db_column='CVE_USUARIO', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='CONTRASEÑA', default='', max_length=8)),
                ('curp', models.CharField(db_column='CURP', max_length=18, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('appaterno', models.CharField(db_column='APELLIDO_PATERNO', max_length=50)),
                ('apmaterno', models.CharField(db_column='APELLIDO_MATERNO', max_length=50)),
                ('edad', models.CharField(db_column='FECHA_NACIMIENTO', max_length=2)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=18)),
                ('alta', models.SmallIntegerField(db_column='ALTA', null=True)),
                ('fechaalta', models.DateTimeField(auto_now_add=True, db_column='FECHA_ALTA', max_length=19, null=True)),
                ('escolaridad', models.ForeignKey(db_column='CVE_ESCOLARIDAD', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catescolaridad')),
                ('estatus', models.ForeignKey(db_column='CVE_ESTATUS', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catestatus')),
                ('institucion', models.ForeignKey(db_column='CVE_INSTITUCION', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catinstitucion')),
                ('perfil', models.ForeignKey(db_column='CVE_PERFIL', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catperfil')),
                ('sexo', models.ForeignKey(db_column='CVE_SEXO', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catsexo')),
            ],
            options={
                'db_table': 'Historico_Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cveusuario', models.BigAutoField(db_column='CVE_USUARIO', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=50, unique=True)),
                ('curp', models.CharField(db_column='CURP', max_length=18, unique=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('apmaterno', models.CharField(db_column='APELLIDO_PATERNO', max_length=50)),
                ('appaterno', models.CharField(db_column='APELLIDO_MATERNO', max_length=50)),
                ('edad', models.CharField(db_column='FECHA_NACIMIENTO', max_length=2)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=18, unique=True)),
                ('fechaalta', models.DateTimeField(auto_now_add=True, db_column='FECHA_ALTA', max_length=19, null=True)),
                ('alta', models.SmallIntegerField(db_column='ALTA', null=True)),
                ('fechabaja', models.DateTimeField(db_column='FECHA_BAJA', max_length=19, null=True)),
                ('baja', models.SmallIntegerField(db_column='BAJA', null=True)),
                ('escolaridad', models.ForeignKey(db_column='CVE_ESCOLARIDAD', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catescolaridad')),
                ('estatus', models.ForeignKey(db_column='CVE_STATUS', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catestatus')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('institucion', models.ForeignKey(db_column='CVE_INSTITUCION', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catinstitucion')),
                ('perfil', models.ForeignKey(db_column='CVE_PERFIL', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catperfil')),
                ('sexo', models.ForeignKey(db_column='CVE_SEXO', on_delete=django.db.models.deletion.CASCADE, to='admin_sistema.catsexo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
