# Generated by Django 3.2.8 on 2022-02-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sistema', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apmaterno',
            field=models.CharField(db_column='APELLIDO_MATERNO', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='appaterno',
            field=models.CharField(db_column='APELLIDO_PATERNO', max_length=50),
        ),
    ]
