# Generated by Django 3.2.8 on 2022-02-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sistema', '0003_auto_20220210_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apmaterno',
            field=models.CharField(db_column='APELLIDO_MATERNO', max_length=51),
        ),
    ]
