# Generated by Django 3.2.8 on 2022-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sistema', '0004_alter_usuario_apmaterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechacambio',
            field=models.DateTimeField(auto_now=True, db_column='FECHA_CAMBIO', max_length=19, null=True),
        ),
    ]
