# Generated by Django 3.2.8 on 2022-03-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sistema', '0005_usuario_fechacambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechacambio',
        ),
    ]
